equinor/sepes-web

src/components/common/customComponents/SearchWithDropdown.tsx, src/components/dataset/StudySpecificDataset.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/SandboxComponent.tsx
=> fix(study details): fix margins and add missing label

src/components/common/StyledComponents.tsx, src/components/common/customComponents/Dropdown.tsx, src/components/sandbox/Execution.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/DatasetsConfirmed.tsx, src/components/sandbox/components/MoreActions.tsx, src/components/sandbox/components/PolicyComponent.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx
=> feat(sandbox page): update sandbox components and styling page

cypress/integration/createStudy/createStudy.spec.js, cypress/integration/createVm/createVm.spec.js, debug.log, src/components/common/interfaces.ts, src/components/sandbox/Sandbox.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/MoreActions.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/SandboxComponent.tsx, src/components/studyDetails/StudyDetails.tsx, src/services/Api.ts
=> feat(virtual machine): user can now create a vm

src/components/common/Promt.tsx, src/components/dataset/StudySpecificDataset.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/SandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyDetails.tsx
=> feat(all pages): added promt for unsaved changes

cypress/integration/createVm/createVm.spec.js, debug.log, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx
=> test(added vm test): added cypress test

src/components/sandbox/StepBar.tsx
=> fix(sandbox): fixed a spelling error

src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/SandboxComponent.tsx
=> fix(study details): fix margins so page doesn't jump when changing tabs

src/components/studyDetails/CreateSandboxComponent.tsx
ndbox component, the "are you sure you want to leave" promt displays
Closes #172
=> fix(studydetails-sandbox tab): fixed bug when going away from create sa-

cypress/integration/createVm/createVm.spec.js, src/components/dataset/StudySpecificDataset.tsx, src/components/sandbox/components/DeleteSandboxComponent.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx
=> fix(textfields): removed textfield suggestions

src/components/dataset/Datasets.tsx, src/components/home/Home.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/topbar/NavTabs.tsx, src/components/topbar/TopBar.tsx, src/index.tsx, src/services/Api.ts
te study and go to datasets tab
=> feat(new study, datasets): added check if user is authenticated to crea-

src/components/sandbox/components/AddNewVm.tsx
=> fix(actual vm name): added delay on actual vm name

src/components/sandbox/components/AddNewVm.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx
=> fix(create vm): validation and info for fields

package-lock.json, package.json
=> fix(dependencies): updated serveral npm packages to fix security issues

src/components/common/interfaces.ts, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/VmConfig.tsx, src/services/Api.ts
=> feat(virtual machine): added size and disk options

src/components/common/customComponents/Dropdown.tsx, src/components/dataset/DatasetsOverviewTable.tsx, src/components/dataset/StudySpecificDataset.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/studyDetails/SandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/topbar/TopBar.tsx
=> feat: added escape and ctrl+s functionality

src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/VmConfig.tsx
=> fix(create vm): change tab and disable button on create

src/components/common/upload/Dropzone.tsx, src/components/studyDetails/StudyComponentFull.tsx
=> fix(study details): fixed styling

src/components/sandbox/components/AddNewVm.tsx
=> fix(create vm): fixed password validation

src/components/topbar/TopBar.tsx
=> fix(topbar): made top bar a link to homepage. Removed equinor icon

src/components/studyDetails/StudyComponentFull.tsx
=> fix(create study): escape button now works as intended

src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx
=> fix(study details): fixed how components move when resizing window

src/components/studyDetails/CreateSandboxComponent.tsx
this feature will not be implemented in the near future. Will be added back later on
Closes #216
=> fix(create sandbox): removed dropdown list for template

src/components/common/customComponents/DatasetsTable.tsx, src/components/common/customComponents/SandboxTable.tsx
=> fix(studydetails): make name of dataset/sandbox clickable links

src/components/common/CustomLogoComponent.tsx
=> fix(studydetails): changed to fixed size of logo to fix displacement

src/components/dataset/DatasetSidesheetView.tsx, src/components/dataset/DatasetsOverviewTable.tsx, src/components/sandbox/components/DeleteResourceComponent.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/topbar/TopBar.tsx
icking outside of the component
Closes #222
=> fix(all pages): clicking outside pop up components now closes when cl-

src/components/sandbox/components/AddNewVm.tsx
=> feat(create Vm): disabled create button until all fields are populated

src/components/common/helpers.tsx, src/components/dataset/StudySpecificDataset.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/DeleteResourceComponent.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/Overview.tsx
ded to nearest tenth.
Styling change to Study details page
Closes #249 Closes #248 Closes #245
=> feat(create vam): filter is now unchecked first, price estimate is roun-

src/components/common/customComponents/ParticipantTable.tsx, src/components/common/hooks/useWindowDimensions.tsx, src/components/studyDetails/ParticipantComponent.tsx
=> fix(participant): removed email column when resizing

src/components/common/LoadingComponentFullscreen.tsx, src/components/sandbox/components/DeleteResourceComponent.tsx
=> fix: added EDS overlay for Spinner and delete resource components

src/components/sandbox/components/AddNewVm.tsx
=> feat(vm): add explaining text for VM size filter

src/components/home/Home.tsx, src/components/home/StudyComponent.tsx
=> fix:(home page): fixed styling when resizing

src/components/common/hooks/useFetch.tsx, src/components/common/interfaces.ts, src/components/sandbox/Execution.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/DatasetsConfirmed.tsx, src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyDetails.tsx, src/services/Api.ts
=> feat(sandbox): add dataset functionality

src/components/dataset/StudySpecificDataset.tsx
=> fix(datasets): add options for classifications dropdown

src/components/sandbox/Sandbox.tsx, src/components/sandbox/components/VmDetails.tsx
=> fix(vm rules): disable save button on cancel

src/components/common/hooks/useFetch.tsx, src/components/studyDetails/StudyDetails.tsx
=> fix(create study): fixed bug where clicking new study made an api call

src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx, src/services/Api.ts
=> fix(vm): fixed a bug where vm rules reset when status turned to OK

package-lock.json, package.json, src/components/studyDetails/StudyDetails.tsx
=> fix(study): tabs are now remembered when user navigates sepes

src/components/sandbox/components/VmDetails.tsx
=> fix(vm rules): add port validation

src/auth/AuthFunctions.ts, src/components/topbar/NavTabs.tsx
=> fix: issue with token renewal

src/components/sandbox/components/VmDetails.tsx
=> fix(vm rules): disable save button if two rules are equal

src/components/dataset/DatasetsOverviewTable.tsx
=> fix(datasets): remember selected columns filter for the table

src/components/common/helpers.tsx, src/components/dataset/DatasetDetails.tsx, src/components/sandbox/components/VmDetails.tsx
=> fix(vm rules): add input check IP and port number

src/components/common/notify.js
=> fix(notification): remove http code from popup

src/components/common/hooks/useFetchUrl.tsx, src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/dataset/Datasets.tsx, src/components/home/Home.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/DatasetsConfirmed.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyDetails.tsx
=> fix(api calls): fix some cache issues and refactor api call hook

src/components/dataset/DatasetDetails.tsx, src/components/studyDetails/StudyComponentFull.tsx
=> fix(study logo): fixed bug where user did not be able to reselect logo

src/auth/AuthFunctions.ts
it was causing errors when signing in
Closes #351
=> fix(login): removed user.read scope from login url

src/auth/AuthFunctions.ts, src/components/common/upload/FileDropzone.tsx, src/components/dataset/DatasetDetails.tsx
=> feat(files): added progress bar

src/components/common/ErrorBoundary.js, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/VmConfig.tsx
=> fix(sandbox resources): stop calling api if this call fails

src/components/studyDetails/DataSetComponent.tsx
=> fix(study): increase white space when many datasets are added to a study

src/components/studyDetails/StudyComponentFull.tsx
=> fix(study): moved settings wheel to top right corner

src/components/studyDetails/ParticipantComponent.tsx
=> fix(participants): added fixed width of add participant button

package-lock.json, package.json, src/components/dataset/DatasetsOverviewTable.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/DatasetsConfirmed.tsx, src/components/sandbox/components/PolicyComponent.tsx, src/components/sandbox/components/ResourcesComponent.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx, src/components/topbar/NavTabs.tsx, src/styles/Table.scss
=> fix: add table hover color and make entire rows clickable

src/components/studyDetails/Tables/SandboxTable.tsx
=> fix: make entire sandbox cell in a study clickable

src/components/dataset/DatasetDetails.tsx
=> fix(dataset): add tooltip with status of the storage account

src/auth/AuthFunctions.ts, src/components/common/NoApi.tsx, src/index.tsx, src/services/Api.ts
=> fix: add a "unable to reach api" page if the api can not be reached

src/components/common/customComponents/SureToProceed.tsx, src/components/home/Home.tsx
=> fix(homepage): Updated text describing what Sepes is

src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/SandboxComponent.tsx
=> fix(study): some margins did not line up between tabs

src/components/common/Promt.tsx, src/components/dataset/DatasetDetails.tsx, src/services/BlobStorage.ts
=> fix(dataset): file upload multiple issues and new text when leaving page during download

src/components/sandbox/components/AddNewVm.tsx
=> fix(vm): disable create vm button until price of the vm is calculated.

src/components/sandbox/StepBar.tsx, src/components/sandbox/components/VmDetails.tsx
=> fix(vm): remove hover color on rules

src/components/studyDetails/StudyComponentFull.tsx
=> fix(study): disable deletion of study when there are sandboxes active

src/components/dataset/DatasetDetails.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/StudyDetails.tsx
=> fix: memory leak for results and learnings and getting files in dataset

src/components/home/StudyComponent.tsx
=> fix(studyList): change icon for hidden/not hidden study

src/components/sandbox/components/VmDetails.tsx
Fixed issue where save button was enabled across all vms when making change to one vm's rules. Also added promt for unsaved changes
Closes #635
=> fix(vm): issue with vm rules state

src/components/dataset/DatasetDetails.tsx
=> fix(dataset): cache sas token for some times to speed up file upload

src/components/common/CustomLogoComponent.tsx, src/components/common/upload/ImageDropzone.tsx, src/components/home/Home.tsx
It would overlap the upload component. Also show preview of the photo without stretching it
Closes #649
=> fix(logo): issue when uplading a transparent logo to a study.

src/auth/AuthFunctions.ts, src/components/common/CustomLogoComponent.tsx, src/components/common/upload/Dropzone.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/services/Api.ts
=> feat(study): users can now remove logo from study

src/components/home/Home.tsx
=> fix(homepage): issue with margin

src/components/dataset/DatasetDetails.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/services/Api.ts, src/services/BlobStorage.ts
Send delete requests directly to blob storage insteand of api
Closes #660
=> fix(dataset): Improve delete file requests

src/components/common/StyledComponents.tsx, src/components/sandbox/Execution.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/sandbox/components/ResourcesComponent.tsx
=> feat(sandbox): add retry functionality for vms

src/components/sandbox/StepBar.tsx, src/components/sandbox/components/VmProperties.tsx
Added tooltip when a user tries to delete vm and sandbox without permission
Closes #670
Closes #671
=> fix(sandbox): new tooltips for access control

src/components/common/CustomLogoComponent.tsx, src/components/common/upload/ImageDropzone.tsx, src/components/home/StudyComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx
Tall logos would look weird and cover the change logo button
Closes #672
=> fix(study): issue with logo component

src/components/sandbox/StepBar.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/SandboxComponent.tsx
Fixed margin with some buttons. Overlay for more options did not get placed correctly
Closes #684
Closes #687
=> fix: multiple style issues

src/components/dataset/CreateEditDataset.tsx
=> fix(dataset): re-enable cancel if create fails

src/components/sandbox/StepBar.tsx
Also added better tooltips for why this button is disabled
Closes #668
=> fix(sandbox); issues with disabeling and enabeling make available button

src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/components/Dataset.tsx
=> fix(sandbox): newly created dataset would not show before refresh

src/components/sandbox/Sandbox.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx
Center retry button for retrying vms. Removed margin that appeared when clicking make available. Pasting long texts to study description will now cut off text instead of not doing anything
Closes #710
Closes #707
Closes #706
Closes #702
=> fix: different bugs and styling issues

src/components/studyDetails/DataSetComponent.tsx
=> fix(dataset): disable create when study has no wbs

src/components/sandbox/components/DatasetsConfirmed.tsx
=> fix(sandbox): remove hover datasets confirmed

src/index.tsx
=> fix: add loading screen to first permission call

src/components/common/upload/Dropzone.tsx
=> fix(study): logo margin

src/components/common/notify.js, src/components/common/upload/Dropzone.tsx, src/components/sandbox/Execution.tsx, src/components/sandbox/components/DatasetsConfirmed.tsx, src/components/sandbox/components/PolicyComponent.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/sandbox/components/VmProperties.tsx
=> fix(sandbox): dataset policy text lineshift issue

package-lock.json, package.json, src/App.tsx, src/components/common/staticValues/commonLinks.ts, src/components/dataset/CreateEditDataset.tsx, src/components/releaseNotes/ReleaseNotes.tsx, src/components/topbar/TopBar.tsx
=> feat: add release notes

src/auth/AuthFunctions.ts, src/components/common/hooks/useFetch.tsx, src/components/common/hooks/useFetchUrl.tsx, src/components/common/notify.js, src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyDetails.tsx
=> fix: add http error to notification component

src/auth/AuthFunctions.ts, src/components/common/customComponents/Dropdown.tsx, src/components/common/helpers.tsx, src/components/dataset/CreateEditDataset.tsx, src/components/home/Home.tsx, src/components/sandbox/components/VmProperties.tsx
=> fix: console errors

src/auth/AuthFunctions.ts
Some logic uses the failed response to better user experience
=> fix: return response even if api calls fails

.eslintrc.js, src/components/common/upload/DropzoneFile.tsx, src/components/sandbox/Execution.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/sandbox/components/ResourcesComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/serviceWorker.ts
This has been allowed by anyone to click, now it will only be allowed to certain roles
=> fix(sandbox): check permission for resource retry mechanism

src/components/common/helpers/datasetHelpers.tsx, src/components/common/helpers/helpers.tsx, src/components/dataset/DatasetDetails.tsx, src/services/BlobStorage.ts, src/tests/unit_test/datasetHelpers.test.tsx
=> feat(dataset): support folders in file upload

src/components/common/helpers/datasetHelpers.tsx, src/components/dataset/DatasetDetails.tsx, src/services/BlobStorage.ts, src/tests/unit_test/datasetHelpers.test.tsx
=> fix(dataset): issue with loading bar when uploading many files

src/components/dataset/DatasetDetails.tsx
Also fixed an issue with deleting dataset while uploading files
Closes #803
Closes #798
=> feat(dataset): add search for files

src/components/common/informationalComponents/GeneralError.tsx, src/components/common/informationalComponents/NoAccess.tsx, src/components/common/informationalComponents/NoApi.tsx, src/components/common/informationalComponents/NotFound.tsx
=> fix: styling and centering text of error/noaccess pages

src/components/common/helpers/datasetHelpers.tsx, src/components/dataset/DatasetDetails.tsx, src/services/BlobStorage.ts
Very useful when uploading many files. Before you would have to scroll and look at each individual progress to see if upload was finished. Now you can see combind progress at the top
=> feat(dataste): Added total progress bar for file upload

src/components/studyDetails/StudyComponentFull.tsx, src/services/Api.ts
hard delete is currently not implemented an exposed
=> fix(study): delete button changed to target the soft delete method

src/components/dataset/DatasetDetails.tsx
=> fix(dataset): issue with size being undefined on upload

src/components/common/helpers/datasetHelpers.tsx, src/components/dataset/DatasetDetails.tsx, src/services/BlobStorage.ts
=> fix(dataset): fix issues and performance of file overview and search

src/components/dataset/DatasetDetails.tsx
Searching for a file did not work correctly with case sensitivity
=> fix(dataset): Issue with search and infinity scroll on file upload

src/components/common/staticValues/commonLinks.ts, src/components/topbar/TopBar.tsx
This will make it easier to report bugs/features for users
Closes #799
=> feat: add link to github's create an issue for users to report bugs

cypress/integration/createStudy/createStudy.spec.js, cypress/integration/createVm/createVm.spec.js, cypress/integration/dataset/createDataset.spec.js, package-lock.json, package.json, src/components/topbar/TopBar.tsx
Chaning auth flow to PCKE caused issue with running cypress tests
=> fix: cypress tests and update to new version

src/components/studyDetails/CreateSandboxComponent.tsx
=> fix(sadbox): close create sandbox dialog when clicking create

.github/workflows/test.yml
=> fix: Pick specific version of jest reporter

src/components/sandbox/StepBar.tsx
=> fix(sandbox): make available disabled bug

src/components/common/interfaces.ts, src/components/topbar/TopBar.tsx, src/index.tsx
=> fix: change name to email in top bar and use api response

src/components/common/customComponents/CustomLogoComponent.tsx
=> fix: vertically align study logos

cypress/integration/quickRunningTests/createStudy/createStudy.spec.js, cypress/support/commands.js, src/auth/AuthFunctions.ts
=> fix(study): not redirecting after delete

src/components/sandbox/components/AddNewVm.tsx
=> fix(create vm): center text in helper text box

src/components/common/helpers/studyHelpers.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/VmProperties.tsx
=> fix(vm): more options button issue

src/components/common/helpers/helpers.tsx, src/components/common/helpers/sandboxHelpers.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx
Make it obvious that name of different resources are invalid. Also make dashes allowed as vm names
Closes #945
Closes #944
Closes #943
=> fix: Textfield validations

cypress/integration/quickRunningTests/createStudy/createStudy.spec.js, src/components/Layout.tsx, src/components/home/Home.tsx, src/components/topbar/TopBar.tsx
=> fix: changed to fixed position of topbar and new study component

.github/workflows/cypress.yml
Will run all tests in Edge and firefox
Closes #919
=> test: run nightly tests in different browsers

.github/workflows/cypress.yml
from edge to chromium
Closes #965
=> fix: change cypress test browser

src/components/studyDetails/Overview.tsx, src/components/studyDetails/StudyDetails.tsx, src/tests/component_tests/study/Overview.test.tsx
Results and learnings would not save
Closes #967
=> fix(study): results and learnings bug

.gitignore, src/components/common/customComponents/Dropdown.tsx, src/components/common/helpers/sandboxHelpers.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/VmDetails.tsx
Data disk should not be a required field when creating a vm. Also included a helpertext for when a user wants a data disk. Some styling as well
Closes #980
Closes #977
=> fix(vm): remove data disk as a requirement

.github/workflows/cypress.yml
Run all tests when you trigger this workflow manually. Makes it easy to create a coverage raport with all files
=> fix: run lon running tests on manual trigger

src/components/common/customComponents/Dropdown.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/sandbox/components/VmDetails.tsx
Fetching ip address would sometimes not work resulting in endlessly waiting for it
Closes #978
=> fix(vm): added retry mechanism for ip address

src/components/common/informationalComponents/NoAccess.tsx
Add more description to make it easier for the user to understand why he/she do no have access to view a page/do an action
=> fix: better explain no access page

.github/workflows/cypress.yml, cypress.dev.json, cypress.json, runcypress.ps1, src/functions/helpers.ps1, src/functions/text.ps1
With mock user. Also added back failing firefox tests
=> test: create script to run cypress locally

cypress/integration/longRunningTests/checkValuesAfterRefresh.spec.js, cypress/integration/longRunningTests/datasetFileUpload.spec.js, cypress/integration/longRunningTests/makeAvailable.spec.js, cypress/integration/quickRunningTests/createStudy/createStudy.spec.js, cypress/support/commands.js, runcypress.ps1
=> test: refreshes page after action to ensure data being saved

.github/workflows/cypress.yml, cypress/support/commands.js, cypress_chromium.dev.json, runcypress.ps1, src/components/topbar/TopBar.tsx
Only display if it is a develop enivorment (not production).
Closes #1006
=> fix: add enviroment to the top bar

.gitignore, cypress/support/commands.js, src/components/common/helpers/helpers.tsx, src/components/dataset/CreateEditDataset.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/studyDetails/StudyComponentFull.tsx
User could write as long of a dataset name that they wanted, causing an error
Closes #1010
=> fix(dataset): no name length validation

src/components/Layout.tsx, src/components/common/helpers/sandboxHelpers.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/components/AddNewVm.tsx
=> fix(vm): data disk should not be required

src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyDetails.tsx
If there is a dataset or sandbox in the study, you can no longer change the wbs. Delete all resources and then you can change the wbs
=> fix(study): not allow changing wbs after creating resources

src/components/common/helpers/helpers.tsx, src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/StudyComponentFull.tsx
This should be allowed
Closes #1041
=> fix: allow dashes in study name

src/components/sandbox/components/AddNewVm.tsx
=> fix(vm): add loading icon when validating username

src/components/common/customComponents/DeleteResourceComponent.tsx, src/components/sandbox/components/VmProperties.tsx
Tooltip saying if you do not have access to delete vm/reset password and reset password is not available yet did not display when expected
Closes #1043
=> fix(vm): tooltips not displaying for more actions

src/components/common/customComponents/AsyncSelect.tsx, src/components/studyDetails/ParticipantComponent.tsx
MS graph required 3 characters before searching, we should do the same
Closes #1070
=> fix(participants): not search before writing three charachters

cypress/integration/quickRunningTests/createStudy/createStudy.spec.js, cypress/integration/quickRunningTests/createVm/createVm.spec.js, cypress/integration/quickRunningTests/rbacTests/studyViewer.spec.js, cypress/support/commands.js, src/components/common/upload/DropzoneFile.tsx, src/components/dataset/DatasetDetails.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmProperties.tsx
=> test: studyviewer permissions

src/components/studyDetails/ParticipantComponent.tsx, src/services/Api.ts, src/services/ApiCallStrings.ts
=> refactor(study): new url for participant endpoints

src/components/studyDetails/StudyComponentFull.tsx
=> fix: ran unnecessary validation of wbs on save

.github/workflows/cypress.yml, .github/workflows/test.yml, README.md
=> test: add label for not running tests

package-lock.json, package.json
=> fix: update eds to 0.13.1

src/components/sandbox/components/VmProperties.tsx
Button was disabled when it should have been enabled
Closes #1125
=> fix(vm): reset password button disabled issue

.github/workflows/cypress.yml, cypress_chromium.dev.json
=> test: Cypress - save video as artifact

src/components/studyDetails/StudyComponentFull.tsx
=> fix: tooltip for loading icon when validating wbs

src/components/common/interfaces.ts, src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/Dataset.tsx, src/components/studyDetails/StudyDetails.tsx
=> fix: add navigation breadcrumbs sandbox datasets

cypress/integration/longRunningTests/makeAvailable.spec.js
=> test: make available button disabled issue

src/components/releaseNotes/ReleaseNotes.tsx, src/tests/component_tests/study/Overview.test.tsx
=> test: comment back overview test

src/components/studyDetails/StudyComponentFull.tsx
=> fix(study): align some margins on edit mode

.github/workflows/cypress.yml, cypress/integration/longRunningTests/checkValuesAfterRefresh.spec.js, cypress/support/commands.js, src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx
=> test: checkvaluesafterrefresh test - prevent login redirect

src/components/dataset/DatasetInformation.tsx
=> fix(dataset): tooltip for storage account status did not display

cypress/fixtures/rbac/vendorContributor/dataset.json, cypress/fixtures/rbac/vendorContributor/permissions.json, cypress/fixtures/rbac/vendorContributor/study.json, cypress/integration/longRunningTests/rbacTests/vendorContributor.spec.js, src/components/common/customComponents/AsyncSelect.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/studyDetails/ParticipantComponent.tsx
=> test: add vendor contributor test and fix vendor admin test

.github/workflows/cypress.yml, cypress.dev.json, cypress.json, cypress/integration/quickRunningTests/createStudy/createStudy.spec.js, cypress_chromium.dev.json
=> test: add retry mechanism to cypress tests

src/index.tsx
=> fix: issue with displaying correct info when api is not reacheable

src/components/common/ErrorBoundary.js
=> fix: go back button on general error page did not reload page

src/components/sandbox/StepBar.tsx
=> fix: center costanalysis link

src/components/sandbox/components/VmConfig.tsx
When clicking make available, the add new vm and vm details will disappear and reappear while loading
Closes #1220
=> fix(sandbox): make available ui bug

cypress/support/commands.js, src/components/common/customComponents/infoDisplayComponents/BreadcrumbTruncate.tsx, src/components/common/customComponents/infoDisplayComponents/TextTruncate.tsx, src/components/common/helpers/helpers.tsx, src/components/common/staticValues/lenghts.ts, src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/home/StudyComponent.tsx, src/components/sandbox/StepBar.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx
Dataset names can no be up to 128 charachter. Same as with study and sandbox names
=> fix: truncate values when they exceed a specific limit

src/components/dataset/DatasetFileList.tsx
Button was also not aligned with the file name
Closes #1223
=> fix(dataset): remove file button circle went outside of component

src/components/common/Promt.tsx, src/components/common/helpers/sandboxHelpers.tsx, src/components/common/staticValues/types.ts, src/components/sandbox/Sandbox.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx
Url changed even if you clicked "stay" at the unsaved changes prompt
Closes #1216
Closes #1233
=> fix: issue with prompt

src/components/dataset/CreateEditDataset.tsx, src/components/sandbox/Sandbox.tsx, src/components/studyDetails/StudyDetails.tsx
=> fix: display prompt if user leaves page when request is in progress

src/components/studyDetails/ParticipantComponent.tsx
=> fix: tooltip for participant role did not display

.github/workflows/cypress-tests.yml, src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/CreateSandboxComponent.tsx
=> fix(study): add tooltip for not all required fields filled

src/components/dataset/CreateEditDataset.tsx
Displays if not all required fields are filled
Closes #1305
=> fix(dataset): add tooltip to create/save button

src/components/sandbox/Execution.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/ResourceItemComponent.tsx, src/components/sandbox/components/ResourcesComponent.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/sandbox/components/VmProperties.tsx
A rerender of the search component caused displaying all results even when the users had written a searchword in. This happen in VM and DISK select components
Closes #1314
=> fix(sandbox): os search issue

src/components/common/helpers/helpers.tsx, src/components/common/helpers/sandboxHelpers.tsx, src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/tests/mocks/study/study-mocs.ts, src/tests/unit_test/sandboxHelpers.test.tsx
=> fix: disable create sandbox when sanbox name exists

src/components/common/helpers/helpers.tsx, src/components/common/helpers/sandboxHelpers.tsx, src/components/sandbox/components/AddNewVm.tsx, src/tests/mocks/sandbox/sandbox-mocks.ts, src/tests/unit_test/helpers.test.tsx, src/tests/unit_test/sandboxHelpers.test.tsx
=> fix: disable create vm if name already is in use

cypress/integration/longRunningTests/makeAvailable.spec.js, src/components/common/helpers/datasetHelpers.tsx, src/components/dataset/CreateEditDataset.tsx, src/components/studyDetails/DataSetComponent.tsx, src/tests/unit_test/datasetHelpers.test.tsx
=> fix(dataset): disable create button if name is taken

src/components/common/StyledComponents.tsx, src/components/common/customComponents/Dropdown.tsx, src/components/common/notify.js, src/components/common/upload/DropzoneFile.tsx, src/components/dataset/DatasetDetails.tsx, src/components/dataset/DatasetOverviewPage/DatasetsOverviewTable.tsx, src/components/home/StudyComponent.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx, src/components/topbar/TopBar.tsx
=> refactor: remove unnecessary EDS icons imports

src/components/sandbox/components/AddNewVm.tsx
=> fix: add tooltip for create vm when it is in progress

src/components/common/staticValues/commonLinks.ts, src/components/topbar/TopBar.tsx
=> feat: add link to documentation

src/components/common/table/DataTable.tsx, src/components/common/table/Pagination.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx
If you add many participants to a study, the page would get longer and longer. To resolve this, pagination is added
Closes #1387
=> feat: add sorting and pagination to participant table

src/auth/AuthFunctions.ts, src/components/common/helpers/helpers.tsx, src/components/common/notify.js
=> refactor: change notification type based on error

src/components/common/customComponents/Password.tsx, src/components/sandbox/components/AddNewVm.tsx
extract password field to a separate component and add helper text
closes #1395
=> feat(vm):add helper text to the password field

src/components/topbar/TopBar.tsx
=> feat: display current roles in top bar

src/components/common/constants/HelperTexts.ts, src/components/common/constants/StepBarTexts.ts, src/components/common/constants/StudyTextSnippets.ts, src/components/common/constants/TooltipTitleTexts.ts, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyTextSnippets.ts
refactor texts to constants
closes #1431
=> refactor:separate texts in to constants

README.md
=> docs: how to add environment variables

cypress/plugins/index.js, cypress/support/index.js, package-lock.json, package.json
=> fix: remove cypress-plugin-retries

src/components/sandbox/components/AddNewVm.tsx
add a warning to vm name field cannot be changed once created
closes #1363
=> feat(vm):add warning to vm name text field

src/components/common/interfaces.ts, src/components/common/table/DataTable.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx
=> feat(study): be able to sort data set list by column

src/components/common/table/DataTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx
=> feat(study): be able to sort sandbox list by column

src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/StudyFull.tsx, src/tests/mocks/study/study-mocs.ts, src/tests/unit_test/studyHelpers.test.tsx
=> fix: instantly disable save study when typing in the wbs field

src/components/common/constants/StudyFeatureToggle.ts, src/components/studyDetails/DataSet.tsx
=> refactor: add standard dataset functionality as a feature toggle

src/components/sandbox/Execution.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/Resources.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/services/Api.ts, src/store/index.ts, src/store/resources/resourcesSelectors.ts, src/store/resources/resourcesSlice.ts, src/store/sandboxes/sandboxesSlice.ts, src/tests/component_tests/sandbox/Stepbar.test.tsx
adding resources api call to redux state management
closes #1500
=> refactor:add resources api call to state management

.gitignore, deployment/app.js, deployment/package-lock.json, deployment/package.json
adding rate limit up to 40 requests per minute
closes #1469
=> fix: add rate limiting

local.index.js, package-lock.json, package.json
=> fix: add rate limit

src/components/studyDetails/DataSet.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/Sandbox.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx, src/tests/component_tests/study/DatasetComponent.test.tsx, src/tests/component_tests/study/Overview.test.tsx, src/tests/component_tests/study/SandboxComponent.test.tsx, src/tests/component_tests/study/SandboxTable.test.tsx
fix navigation to the dataset page while editing a study
closes #1478
=> fix(dataset): fix navigation to dataset page

src/components/common/table/DataTable.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/Sandbox.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx, src/tests/component_tests/study/SandboxTable.test.tsx
hide pagination if there are less than 10 items
Closes #1476, #1467
=> fix: pagination fix and some refactor

src/components/dataset/CreateEditDataset.tsx
when creating a dataset, clearly shoe the dataset name validation to the the use.
Closes #1461
=> fix(dataset): fix name validation

src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx, src/components/studyDetails/Tables/SandboxTable.tsx
error displayed to the user when creating a new sandbox, though the sandbox creation is successful
Closes #1526
=> fix: error creating new a sandbox

Dockerfile, radixconfig.yaml, src/App.tsx, src/auth/AuthConfig.tsx, src/auth/AuthFunctions.ts, src/components/common/helpers/helpers.tsx, src/components/topbar/TopBar.tsx
* ci: use production environment variables in prod
=> ci: use production environment variables in prod (#1533)

src/components/sandbox/Sandbox.tsx, src/components/studyDetails/StudyFull.tsx
Fix to long lasing screen when creating a study. Now the user has to wait until the WBS validated when creating a study.
Closes #1464
=> fix(study): fix long loading screen

src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/store/datasets/datasetsSelectors.ts, src/store/datasets/datasetsSlice.ts, src/store/index.ts, src/tests/component_tests/dataset/CreateEditDataset.test.tsx, src/tests/mocks/mockStore.ts
=> refactor: add data set to redux state management

cypress/fixtures/study/availableRoles.json, cypress/integration/longRunningTests/rbacTests/vendorAdmin.spec.js, cypress/support/mocking.js, src/tests/component_tests/sandbox/Stepbar.test.tsx
=> refactor: mock vendor admin cypress test

src/components/common/table/DataTable.tsx, src/components/dataset/DatasetDetails.tsx, src/store/index.ts, src/store/usersettings/userSettingsSelectors.ts, src/store/usersettings/userSettingsSlice.ts
persist folder view mode in localstorage
Closes #1455
=> feat(dataset): save folder view mode

src/components/studyDetails/StudyFull.tsx
infinite loading screen when create study throws an api error
Closes #1549
=> fix(study): infinite loading screen when create study throws error

src/components/topbar/TopBar.tsx, src/services/serviceNowApiService.ts
add feedback form
Closes #1356
=> feat: add feedback form

src/components/topbar/TopBar.tsx
- add feedback link/icon next to documentation button
- display the service now reference to the user
Closes #1559
=> feat: improvements to send feedback UI

src/components/topbar/TopBar.tsx
clarify user how to follow up the task in ServiceNow
Closes #1562
=> feat: feedback form improvements

src/components/common/staticValues/types.ts, src/components/sandbox/components/ResourceItem.tsx, src/components/sandbox/components/Resources.tsx
show vm creation error and to retry clearly to the user
Closed #1565
=> feat(vm): show vm creation error

package-lock.json, package.json, src/components/studyDetails/StudyDetails.tsx, src/components/studyDetails/StudyFull.tsx, src/services/Api.ts, src/tests/component_tests/study/StudyComponentFull.test.tsx
this will prevent fetching study data twice
Closes #1496
=> refactor(study): use response from create study

runcypress.ps1, src/components/home/Home.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/StepBar.tsx, src/components/studyDetails/CreateSandbox.tsx, src/components/studyDetails/StudyDetails.tsx, src/functions/helpers.ps1, src/services/Api.ts, src/store/resources/resourcesSlice.ts, src/store/sandboxes/sandboxesSlice.ts, src/tests/component_tests/sandbox/Stepbar.test.tsx, src/tests/mocks/mockStore.ts
this will prevent sending an extra request to fetch the sandbox
Closes #1498
=> refactor(sandbox): use the response from the sandbox create request

.github/workflows/cypress-tests.yml, package-lock.json, package.json, src/components/studyDetails/StudyDetails.tsx
=> refactor(study): add cache back

package-lock.json, package.json, src/components/studyDetails/StudyDetails.tsx
axios upgrade failing cypress test
Closes #1585
=> fix: axios upgrade failing cypress test

src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/sandbox/Sandbox.tsx, src/components/studyDetails/StudyDetails.tsx, src/services/Api.ts
use response from create dataset api call
Closes #1497
=> refactor(dataset): use response from create dataset

src/components/dataset/DatasetDetails.tsx, src/components/dataset/DatasetFileList.tsx
show file upload completion clearly to the user
Closes #1574
=> fix(dataset): file upload progress complete

runcypress.ps1, src/components/studyDetails/Overview.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/studyDetails/StudyFull.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx, src/components/studyDetails/Tables/ParticipantTable.tsx
error creating new study
Closes #1593
=> fix(study): error creating new study

README.md
=> refactor: update gist

src/components/sandbox/components/AddNewVm.tsx
being able to deselect the VM when creating a new VM
Closes #1599
=> fix(vm): deselect disk when creating a new VM

src/components/common/Prompt.tsx, src/components/dataset/CreateEditDataset.tsx, src/components/dataset/DatasetDetails.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx, src/components/studyDetails/CreateSandbox.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/Sandbox.tsx, src/components/studyDetails/StudyDetails.tsx, src/components/studyDetails/StudyFull.tsx, src/store/usersettings/userSettingsSelectors.ts, src/store/usersettings/userSettingsSlice.ts, src/tests/component_tests/sandbox/Stepbar.test.tsx, src/tests/component_tests/study/Overview.test.tsx, src/tests/component_tests/study/SandboxComponent.test.tsx, src/tests/component_tests/study/StudyComponentFull.test.tsx
add unsaved state change to redux
Closes #1602
=> refactor: add unsaved change state to redux

src/components/sandbox/components/VmDetails.tsx, src/store/virtualmachines/virtualMachinesSlice.ts
update vm rules in redux store
Closes #1610
=> refactor(vm): update vm rules in redux store

package-lock.json, package.json, src/components/common/Prompt.tsx, src/components/topbar/TopBar.tsx
update eds-core-react
Closes #1612
=> build: update eds-core-react to v0.18.0

src/components/sandbox/components/VmDetails.tsx
fixed not being able to create firewall rules
Closes #1615
=> fix(vm): fix vm firewall creation error in frontend

CHANGELOG.md, package-lock.json, package.json
Resolve master and develop conflicts.
=> ci: resolve master dev conflicts

cypress/integration/longRunningTests/rbacTests/studyViewer.spec.js, cypress/integration/longRunningTests/rbacTests/vendorAdmin.spec.js, package-lock.json, package.json
removing some checks because timeouts
Closes #1561
=> test: fix failing ui tests

src/components/sandbox/components/Dataset.tsx
fixed shape of dataset prop and filtering logic when toggling datasets in sandbox
Closes #1626
=> fix(sandbox): enable make available button when criteria is met

package.json, src/components/sandbox/components/VmProperties.tsx
Refactored VmProperties.tsx to use flexbox instead of grid
Added new styled component TextWrapper to allow wrapping
Implemented method to create row templates from title, value and style
Added npm script to run lint
Closes #1622
=> fix(vm): properties display

package-lock.json, package.json
Replaced node sass with dart-sass to fix vulnerabillity. Moved react-scripts to devDependencies
=> chore: replace node sass
