equinor/sepes-web

LICENSE
Use same license as sepes-api
Closes: #95
=> feat(license): add MIT license

public/index.html
From "Web site created using create-react-app" to "Emerging IT Sandbox"
Closes #969
=> fix: change standard link description

cypress/integration/longRunningTests/checkValuesAfterRefresh.spec.js, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/ResourcesComponent.tsx
The page would look weird if there were many data sets or resources (vms). Added a scroolbar to keep the page the same size, but still able to see all resources and data sets.
Closes #1024
=> fix(sandbox): add scroll effect to data set and resource list

src/components/studyDetails/ParticipantComponent.tsx
The text would remain there when it should dissapear after typing
Closes #1033
=> fix(study): clear participant search box after typing

src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/StudyComponentFull.tsx
You should be allowed to create a wbs with an invalid wbs. It is only when you have active resources that you should be required to have a valid wbs
Closes #1036
=> fix:(study): create button disabled with invalid wbs

src/components/common/customComponents/DeleteResourceComponent.tsx, src/components/home/StudyComponent.tsx, src/components/sandbox/components/Dataset.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/Tables/DatasetsTable.tsx
Long study, sandbox and data set names would make the ui look weird. Truncate them and add tooltips. Deleting a resource with a very long name was also buggy. Name went outside window
Closes #1042
Closes #1013
=> fix: truncate and fix ui issues with long names

src/components/sandbox/components/ResourceItemComponent.tsx
This would make it easier to understand why the link is not going anywhere as of yet. (Since the vm is not ready)
Closes #1049
=> fix(sandbox): add tooltip to inactive VM links

src/components/common/StyledComponents.tsx, src/components/common/staticValues/types.ts, src/components/sandbox/components/ResourceItemComponent.tsx
Previously there have only been icons for in progress and done. Not for resources that are waiting to be started
Closes #1121
=> fix(sandbox): add new queue icon for resources

src/components/sandbox/components/ResourcesComponent.tsx
Only happened when a resource failed and the retry button appeared
Closes #1136
=> fix: remove horizontal scroll on resource overview

src/components/studyDetails/DataSetComponent.tsx, src/components/studyDetails/StudyComponentFull.tsx, src/components/studyDetails/StudyDetails.tsx
This prevents some ugly side effects that can happen if you try to create a sandbox when changing from an invalid to valid wbs
Closes #1097
=> fix(study): disable create sandbox and dataset when saving study

src/components/common/helpers/helpers.tsx, src/components/dataset/CreateEditDataset.tsx, src/components/studyDetails/CreateSandboxComponent.tsx, src/components/studyDetails/Overview.tsx, src/components/studyDetails/StudyComponentFull.tsx
If a user tries to create a study, sandbox or a dataset with a name over a certain length, a text will display recommending going for a shorter name
Closes #1148
=> fix: add helpertext when typing long inputs

src/components/releaseNotes/ReleaseNotes.tsx
Makes it easier to compare api and web changes when you can switch back and forth without scrolling up
Closes #957
=> fix: release notes tabs have now fixed position

src/components/studyDetails/Overview.tsx
This could be dragged so the page looked very weird. Easiest to disable it
Closes #1154
=> fix: disable resize of results and learnings textfield

src/components/sandbox/components/VmConfig.tsx, src/components/sandbox/components/VmDetails.tsx
If the user entered a valid rule and went back and forth between vm tabs, it will be disabled until the user did a change
Closes #1212
=> fix: issue with disabled save button on vm rules

src/components/common/helpers/sandboxHelpers.tsx, src/components/sandbox/components/AddNewVm.tsx
The UI already tells the users what the vm name will be, regardless of what they type
Closes #1230
=> fix: stop disabeling create button with invalid vm name

src/components/sandbox/components/VmConfig.tsx
=> fix: unsaved vm rules still showes when exiting and reentering a sandbox

src/components/common/helpers/studyHelpers.tsx, src/components/studyDetails/StudyComponentFull.tsx
Wbs input displayed as incorrect when having an empty wbs. But this should be allowed
Closes #1281
=> fix: issue with wbs input

src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/VmProperties.tsx
When hitting enter instead of clicking the delete button, the VM would reappear
Closes #1322
=> fix: issue with deleting vm with enter button

src/components/studyDetails/ParticipantComponent.tsx, src/components/studyDetails/StudyTextSnippets.ts
Before it would say "no options" when for instance writing 2 characters,
and the initial tip is no longer displayed since you started typing
Closes #1264
=> fix: display search tip with less than 3 characters

src/components/sandbox/Sandbox.tsx, src/components/sandbox/StepBar.tsx, src/tests/component_tests/sandbox/Stepbar.test.tsx
The unsaved changes dialog would pop up if there was any and you tried to delete the sandbox. This could result in weird side effects if you clicked stay after deleting sandbox
Closes #1437
=> fix: issue with deleting sandbox with unsaved changes

src/components/studyDetails/Overview.tsx, src/components/studyDetails/StudyFull.tsx
Removed an issue where you can create lineshifts with enter since it instead saves. This is was valid for study description and results and learnings
Closes #1458
Closes #1459
=> fix: remove interfering save shortcut

src/components/common/helpers/sandboxHelpers.tsx, src/components/common/hooks/useFetchUrl.tsx, src/components/sandbox/Sandbox.tsx, src/components/sandbox/SandboxConfig.tsx, src/components/sandbox/StepBar.tsx, src/components/sandbox/components/AddNewVm.tsx, src/components/sandbox/components/Dataset.tsx, src/components/sandbox/components/Policy.tsx, src/components/sandbox/components/VmConfig.tsx, src/store/sandboxes/sanboxesSelectors.ts, src/store/sandboxes/sandboxesSlice.ts, src/tests/component_tests/sandbox/Stepbar.test.tsx
Add sandbox to redux state management. The state is passed down to lot of child components.
closes #1506
=> refactor: add sandbox to state management

src/components/studyDetails/StudyFull.tsx
Fix to long lasing screen when creating a study. Now the user has to wait until the WBS validated when creating a study.
Closes #1464
=> fix(study): fix long loading screen
